matrix:
  include:
    - language: python
      python:
        - "3.6"
      
      # Steps before running script
      before_script:
        - cd .

      # command to install dependencies
      install:
        - pip install -r backend/requirements.txt
      # command to run tests
      script:
        - pytest backend/tests/test_app.py